## My first python code.

In [1]:
print("hello!")

hello!


In [2]:
for i in [0,1,2,3,4]:
    print(i)

0
1
2
3
4


In [3]:
data = ['환자1','환자2','환자3','환자4']
for subj in data:
    print(subj)

환자1
환자2
환자3
환자4


In [4]:
for i in [0,1,2,3]:
    print(i,data[i])

0 환자1
1 환자2
2 환자3
3 환자4


In [5]:
for i in [0,1,2,3]:
    if i<2:
        print(data[i],'is A 유형.')
    else:
        print (data[i],"is B 유형.")
print ("Great!")

환자1 is A 유형.
환자2 is A 유형.
환자3 is B 유형.
환자4 is B 유형.
Great!


In [6]:
for i in range(0,4):
    print(i,data[i])

0 환자1
1 환자2
2 환자3
3 환자4


In [7]:
for i in range(0,4):
    print('환자',i+1)    

환자 1
환자 2
환자 3
환자 4


In [8]:
for i in range(5):
    if i%2 == 0:
        print (i,'is even.')
    else:
        print (i,"is odd.")
print ("Great!")

0 is even.
1 is odd.
2 is even.
3 is odd.
4 is even.
Great!


## 변수

In [9]:
A = ['one', 2, 'three', 'banana']
print(A)
print(A[2])

['one', 2, 'three', 'banana']
three


In [10]:
A[2]='four'
print('변경 후:',A[2])
print(A)

변경 후: four
['one', 2, 'four', 'banana']


In [11]:
B = ('one', 2, 'three', 'banana')
print(B[2])

three


In [12]:
#B[2]='four'

In [13]:
C = {} # create dictionary
C = {'lat': 40.20547, 'lon': -74.76322}
C['lat'] = 40.3054
print(C['lat'])

40.3054


In [14]:
C['lon']=-50; #변경 가능함
print(C)

{'lat': 40.3054, 'lon': -50}


## 숫자 리스트

In [15]:
a=[5,1,3,2,4]
b=a+[4,5,6,1,2]
print(b)

[5, 1, 3, 2, 4, 4, 5, 6, 1, 2]


In [16]:
a[3]

2

In [17]:
nums = [10, 20, 30, 40, 50, 60, 70, 80, 90]
print(nums)
some_nums = nums[2:7]
print(some_nums)
print(nums[0:4])

[10, 20, 30, 40, 50, 60, 70, 80, 90]
[30, 40, 50, 60, 70]
[10, 20, 30, 40]


In [18]:
print(nums[:5]) #equivalent to nums[0:5]
print(nums[-3:])
print(nums[-5:-1])
print(nums[:-2])

[10, 20, 30, 40, 50]
[70, 80, 90]
[50, 60, 70, 80]
[10, 20, 30, 40, 50, 60, 70]


In [19]:
print(nums[::2])
print(nums[1::2]) #step 2
print(nums[1:-3:2]) #step 2
print(nums[::-1]) #reverse
print(nums[-2::-1])
print(nums[-2:1:-3])

[10, 30, 50, 70, 90]
[20, 40, 60, 80]
[20, 40, 60]
[90, 80, 70, 60, 50, 40, 30, 20, 10]
[80, 70, 60, 50, 40, 30, 20, 10]
[80, 50]


## 배열 함수

In [22]:
!pip install numpy

  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/d5/50/8aedb5ff1460e7c8527af15c6326115009e7c270ec705487155b779ebabb/numpy-1.25.2-cp310-cp310-macosx_10_9_x86_64.whl.metadata
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.8/20.8 MB 2.4 MB/s eta 0:00:0000:0100:01


In [23]:
from numpy import *

In [24]:
vec = array([1,2,3])
mat = array([[1,2,3],[4,5,6],[7,8,9]])
print(vec)
print(mat)


[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
ar1 = array([2,4,6])

In [26]:
ar1+2

array([4, 6, 8])

In [27]:
ar1 = array([2,4,6]); ar2 = array([1,2,3])

In [28]:
ar1+ar2

array([3, 6, 9])

In [29]:
ar1*ar2

array([ 2,  8, 18])

In [30]:
ar1/ar2

array([2., 2., 2.])

In [31]:
ar1**ar2

array([  2,  16, 216])

In [32]:
ar3 = (pi/4)*arange(3)
print(ar3)

[0.         0.78539816 1.57079633]


In [33]:
sin(ar3)

array([0.        , 0.70710678, 1.        ])

## 문자열

In [34]:
str='HelloYUMC'

In [35]:
str[2:7]

'lloYU'

In [36]:
str[2:7:2]

'loU'

In [37]:
str[::2]

'HloUC'

In [38]:
str[:7:2]

'HloU'

In [39]:
S="this is a beautiful day."
print(S)
S1=S.capitalize()
print(S1)

this is a beautiful day.
This is a beautiful day.


In [40]:
print(S.upper())

THIS IS A BEAUTIFUL DAY.


In [41]:
print(S.center(35,'#')) #S.center(width[, fillchar])

######this is a beautiful day.#####


In [42]:
print(S.replace('a','A')) #S.replace(froma,tob)

this is A beAutiful dAy.


In [43]:
print(S.count('a')) #S.count(substring [, start-idx [, end-idx]])

3


In [44]:
S.count('a',5,15)
S.count('is') 
S.startswith('T'),S.startswith('Th')
S.endswith('!'),S.endswith('y!')
S.isalpha(), S.isdigit(), S.islower(), S.isspace(), S.isupper()
names = ["Ben", "Chen", "Yaqin"]
", ".join(names)


'Ben, Chen, Yaqin'

In [45]:
dir(S)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',


In [46]:
a = "He found it boring and he left"
loc = a.find("boring")
print(loc)
a = a[:loc] + "fun"
print(a)

12
He found it fun


In [47]:
b = ' and '.join(["cars", "trucks", "motorcycles"])
print(b)

cars and trucks and motorcycles


In [48]:
c = b.split()
print(c)
d = b.split(" and ")
print(d)

['cars', 'and', 'trucks', 'and', 'motorcycles']
['cars', 'trucks', 'motorcycles']


## 문자열 출력 {}

In [49]:
a=1;b=2
print('%d %03d' % (a, b))
print('{} {:03d}'.format(a, b))
print(f'{a} {b:03d}')

1 002
1 002
1 002


In [50]:
name="Park"; age=25; height=178.34
print("My name is " + name +". I’m " , age, "years old")
print("My name is {}. I’m {} years old".format(name,age))
print("My height is {:4.1f}. I’m {:3d} years old".format(height,age))


My name is Park. I’m  25 years old
My name is Park. I’m 25 years old
My height is 178.3. I’m  25 years old


In [51]:
"value=({},{})".format(2,5)

'value=(2,5)'

In [52]:
"value=({1},{0})".format(2,5)

'value=(5,2)'

In [53]:
"value={lati},{longi}".format(lati=35.6,longi=139.6)

'value=35.6,139.6'

## 문자열 출력 f

In [54]:
name="Park"; age=25; height=178.34
str="My name is {name}. I’m {age} years old"
str1=f"My name is {name}. I’m {age} years old"
print(str);print(str1)

My name is {name}. I’m {age} years old
My name is Park. I’m 25 years old


In [55]:
str2=f"My height is {height:4.1f}. I’m {age:3d} years old"
print(str2)
print(f"{name}: {height=:4.1f},{age=:d}y")
print(f"{name!r}: {height=:4.1f},{age=:3d}y")

My height is 178.3. I’m  25 years old
Park: height=178.3,age=25y
'Park': height=178.3,age= 25y


## input

In [58]:
str=input("Please enter #:")
x = int(str)
print("You entered {}".format(x))

Please enter #: 50


You entered 50


In [59]:
a,b=input("Enter two numbers:").split()
a=int(a);b=int(b)
print("You entered two numbers to sum:{}+{}={}".format(a,b,a+b))

Enter two numbers: 20 25


You entered two numbers to sum:20+25=45


## 모음 자료형

In [60]:
a=[1, 3, 5, 7, 11]
b=[0, 1, 'boom']
colors = ['red', 'green', 'gold']

In [61]:
a=[0,2,5]
b=[a,3,4]
print ("b=",b)
print ("b[0][1]=",b[0][1])
#print (b[1][0]) #TypeError: 'int' object is unsubscriptable
c=a+b
print("c=",c)

b= [[0, 2, 5], 3, 4]
b[0][1]= 2
c= [0, 2, 5, [0, 2, 5], 3, 4]


In [62]:
x = [2,3,1]
x.remove(1) # removes the 1, not the item at position 1!!
print(x)
x1=x[:]
print(x1)

[2, 3]
[2, 3]


In [63]:
x.append([5,4]) #insert the object to the end
print(x)
x1.extend([5,4])#insert the elements of the object to the end
print(x1)

[2, 3, [5, 4]]
[2, 3, 5, 4]


In [64]:
x1.sort()
print(x1)
x1.reverse()
print(x1)

[2, 3, 4, 5]
[5, 4, 3, 2]


## 메모리 참조와 형성